#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 14 13:03:41 2019

@author: Andrew
"""

import PIL
from PIL import Image
file="/Users/Andrew/Desktop/Screen Shot 2019-07-31 at 7.53.21 PM.png" 
image=Image.open(file)
print(image)

import inspect
print("The type of the image is " + str(type(image)))
inspect.getmro(type(image))


from IPython.display import display
display(image)

from PIL import ImageFilter

image=image.convert('RGB')
blurred_image=image.filter(PIL.ImageFilter.BLUR)
display(blurred_image)

print("{}x{}".format(image.width, image.height))
display(image.crop((25,50,390,500)))

from PIL import ImageDraw
drawing_object=ImageDraw.Draw(image)
drawing_object.rectangle((25,50,390,500), fill = None, outline ='red')
display(image)

from PIL import ImageEnhance

enhancer=ImageEnhance.Brightness(image)
images=[]

for i in range(0, 10):
    images.append(enhancer.enhance(i/10))
display(images)

first_image=images[0]
from PIL import Image
contact_sheet=PIL.Image.new(first_image.mode, (first_image.width,10*first_image.height))

current_location = 0
for img in images:
    contact_sheet.paste(img, (0, current_location) )
    current_location=current_location+450

contact_sheet = contact_sheet.resize((160,900) )
display(contact_sheet)

contact_sheet=PIL.Image.new(first_image.mode, (first_image.width*3,first_image.height*3))
x=0
y=0


for img in images[1:]:
    contact_sheet.paste(img, (x, y) )
    if x+first_image.width == contact_sheet.width:
        x=0
        y=y+first_image.height
    else:
        x=x+first_image.width
        
contact_sheet = contact_sheet.resize((int(contact_sheet.width/2),int(contact_sheet.height/2) ))        
display(contact_sheet)
